### ISSUE TITLE
Docs: Data examples to show full flow from client->server and server->client

### ISSUE THREAD

**Issue by kristianmandrup** [metasoarous/datsync#2]
Nice to see the new README with API docs.

Next improvement would be to see examples of how a real transaction from client would be sent to server and applied and how it would look in reverse (server-> client).
Perhaps with a simple Todo model.

Also needs example of how common concurrency issues are resolved (optimistic commit/merge?). Cheers :)

**Comment by metasoarous** [comment]
Will do :-)

The optimistic commits/merges may take a little while. Still haven't definitively figured out what I'm going to do there yet. You can take a look at the Wiki for my current thoughts though.

**Comment by metasoarous** [comment]
I'm going to close this for now, since Catalysis has some basic data flow. Do need to add a write example into the live view still (though there is some datview code in catalysis that does this). But let's leave any more specific requests for example type things to Catalysis issues.
